# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61i.proto\x12\x02\x61i\"\x85\x01\n\x0b\x45motionData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x14\n\x0cmain_emotion\x18\x02 \x01(\t\x12\x18\n\x10main_class_ratio\x18\x03 \x01(\x01\x12\x19\n\x11secondary_emotion\x18\x04 \x01(\t\x12\x1d\n\x15secondary_class_ratio\x18\x05 \x01(\x01\"*\n\tUserInput\x12\x1d\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0f.ai.EmotionData\"\x1a\n\x08\x41IOutput\x12\x0e\n\x06report\x18\x01 \x01(\t2?\n\x0e\x41iGuideService\x12-\n\x0eGenerateReport\x12\r.ai.UserInput\x1a\x0c.ai.AIOutputb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMOTIONDATA']._serialized_start=17
  _globals['_EMOTIONDATA']._serialized_end=150
  _globals['_USERINPUT']._serialized_start=152
  _globals['_USERINPUT']._serialized_end=194
  _globals['_AIOUTPUT']._serialized_start=196
  _globals['_AIOUTPUT']._serialized_end=222
  _globals['_AIGUIDESERVICE']._serialized_start=224
  _globals['_AIGUIDESERVICE']._serialized_end=287
# @@protoc_insertion_point(module_scope)
