# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61i.proto\x12\x02\x61i\"?\n\tUserInput\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x1e\n\x05input\x18\x02 \x03(\x0b\x32\x0f.ai.EmotionData\"}\n\x0b\x45motionData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12/\n\x08\x65motions\x18\x02 \x03(\x0b\x32\x1d.ai.EmotionData.EmotionsEntry\x1a/\n\rEmotionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\".\n\x08\x41IOutput\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0e\n\x06report\x18\x02 \x01(\t2C\n\x0e\x41iGuideService\x12\x31\n\x12GetEmotionalReport\x12\r.ai.UserInput\x1a\x0c.ai.AIOutputb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMOTIONDATA_EMOTIONSENTRY']._loaded_options = None
  _globals['_EMOTIONDATA_EMOTIONSENTRY']._serialized_options = b'8\001'
  _globals['_USERINPUT']._serialized_start=16
  _globals['_USERINPUT']._serialized_end=79
  _globals['_EMOTIONDATA']._serialized_start=81
  _globals['_EMOTIONDATA']._serialized_end=206
  _globals['_EMOTIONDATA_EMOTIONSENTRY']._serialized_start=159
  _globals['_EMOTIONDATA_EMOTIONSENTRY']._serialized_end=206
  _globals['_AIOUTPUT']._serialized_start=208
  _globals['_AIOUTPUT']._serialized_end=254
  _globals['_AIGUIDESERVICE']._serialized_start=256
  _globals['_AIGUIDESERVICE']._serialized_end=323
# @@protoc_insertion_point(module_scope)
